"""Prometheus metrics configuration for the application.

This module sets up and configures Prometheus metrics for monitoring the application.
"""

from prometheus_client import Histogram, Gauge, Counter
from starlette_prometheus import metrics, PrometheusMiddleware


# Request metrics
http_request_total = Counter("http_request_total", "Total number of HTTP requests", ["method", "endpoint", "status"])

http_request_duration_seconds = Counter(
  "http_request_duration_seconds", "HTTP request duration in seconds", ["method", "endpoint"]
)

# database_metrics
database_connections = Gauge("database_connections", "Number of active database connections")

# custom business metrics
orders_processed = Counter("orders_processed_total", "Total number of orders processed")

llm_inference_duration_seconds = Histogram(
  "llm_inference_duration_seconds",
  "Time spent processing LLM inference",
  ["model"],
  buckets=[0.1, 0.3, 0.5, 1.0, 2.0, 5.0],
)

llm_stream_duration_seconds = Histogram(
  "llm_stream_duration_seconds",
  "Time spent processing LLM stream inference",
  ["model"],
  buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

session_names_generated_total = Counter(
  "session_names_generated_total",
  "Total session names generated by the LLM",
  ["status"],  # "success" | "error"
)

def setup_metrics (app):
  """Set up Prometheus metrics middleware and endpoints.

  Args:
    app: FastAPI application instance
  """

  # add Prometheus middleware
  app.add_middleware(PrometheusMiddleware)

  # add metrics endpoint
  app.add_route("/metrics", metrics)

